### ISSUE TITLE
I encounted the error when i use the cryspy with QE6.8

### ISSUE THREAD

**Issue by MDuser98** [Tomoki-YAMASHITA/CrySPY#11]
Thank you for developing a so nice tool to predict the structure of crystals.
I install the cryspy 0.10.0 and quantum espresso 6.8 on centos 7.
The combo, pyxtal, pymatgen were also installed normally.
But I can not run the QE_benzene_2_RS_mol example in the folder of cryspy.
The cryspy can generate the structure of benzene, but when i run the command "./crpspy &" for the second time. The cryspy can not be running normally.
In the file of ~/QE_benzene_2_RS_mol/work/000000/job_cryspy.e4000,  I got this message "/var/spool/torque/mom_priv/jobs/4000.node01.SC:行8：pwscf.in: 没有那个文件或目录
sed: 无法读取 stat_job:没有那个文件或目录"

I want to know how to deal with this error.

**Comment by Tomoki-YAMASHITA** [comment]
Could you show me your job_cryspy file?
The error message seems to say "pwscf.in was not found"

**Comment by MDuser98** [comment]
Thank you for your prompt reply.
The content of my job_cryspy file is as follows:
#!/bin/sh
#$ -cwd
#$ -V -S /bin/bash
####$ -V -S /bin/zsh
#$ -N bz_0
#$ -pe smp 8

mpirun -np 20 /home/admin/software/qe/qe68/bin/pw.x  < pwscf.in > pwscf.out

# for QE
if [ -e "CRASH" ]; then
    exit 1
fi

sed -i -e '3 s/^.*$/done/' stat_job


By the way, the pwscf.in file was in the "~/work/000000/ " folder. And I can run the pwscf.in with QE6.8 normally

**Comment by MDuser98** [comment]
Thank you for your prompt reply.
The content of my job_cryspy file is as follows:
#!/bin/sh
#$ -cwd
#$ -V -S /bin/bash
####$ -V -S /bin/zsh
#$ -N bz_0
#$ -pe smp 8

mpirun -np 20 /home/admin/software/qe/qe68/bin/pw.x < pwscf.in > pwscf.out

for QE
if [ -e "CRASH" ]; then
exit 1
fi

sed -i -e '3 s/^.*$/done/' stat_job

By the way, the pwscf.in file was in the "~/work/000000/ " folder. And I can run the pwscf.in with QE6.8 normally

**Comment by Tomoki-YAMASHITA** [comment]
CrySPY just carries out `jobcmd jobfile` in cryspy.in --> e.g. `qsub  job_cryspy`. 
You can run pw.x with the pwscf.in using the command `qsub job_cryspy` in ~/work/000000/, can't you?
I have no idea now.

The error message pointed out line 8: "mpirun -np 20 /home/admin/software/qe/qe68/bin/pw.x < pwscf.in > pwscf.out".
There must be something wrong in this part.

**Comment by MDuser98** [comment]
Emmmm, I mean when i use the command "mpirun -np 20 /home/admin/software/qe/qe68/bin/pw.x < pwscf.in", the calculation can be preformed normally.
when I use the absolute path of the "pwscf.in" file in job_cryspy, the calculation of quantum espresso can be performed normally.
Maybe I need to read the code of cryspy.

**Comment by Tomoki-YAMASHITA** [comment]
Are there job_cryspy and pwscf.in files in ~/work/000000/ ?
If so, please try  the following:
```
cd ~/work/000000
qsub job_cryspy
```

I'm not sure if `qsub` is the right command your machine.
It depends on your environment.

**Comment by MDuser98** [comment]
Thank you for your reply!
I used "qsub job_cryspy" to submit the job_cryspy. It doesn't work. But my TORQUE can work well with Materials Studio. 
I don't know why this happens.

**Comment by Tomoki-YAMASHITA** [comment]
Perhaps there is something wrong in your job_cryspy.
