### ISSUE TITLE
Possible to use with CIF files?

### ISSUE THREAD

**Issue by sgbaird** [Tomoki-YAMASHITA/CrySPY#14]
CIFs as inputs

**Comment by Tomoki-YAMASHITA** [comment]
You have to convert cifs to pkl data.  I am developing the script to convert it.　It will be available soon.

**Comment by sgbaird** [comment]
Thanks!

**Comment by sgbaird** [comment]
@Tomoki-YAMASHITA did you write the script? If so, where can I find it?

**Comment by Tomoki-YAMASHITA** [comment]
@sgbaird 

I forgot the link.

https://github.com/Tomoki-YAMASHITA/CrySPY_utility
Doc for pos2pkl: https://tomoki-yamashita.github.io/CrySPY_doc/cryspy_utility/pos2pkl/

I opened github discussions for CrySPY: https://github.com/Tomoki-YAMASHITA/CrySPY/discussions
If you have any further questions and requests, feel free to write!

**Comment by sgbaird** [comment]
Perfect. Thanks!
