### ISSUE TITLE
The QE input is formatted incorrectly

### ISSUE THREAD

**Issue by ignaciomigliaro** [Tomoki-YAMASHITA/CrySPY#49]
Hello, I have taken great interest in your code and have tried running it with QE but have ran into multiple problems. For example in the code for interface/QE/strucuture.py, the code has it that the order of the elements are wrong. This is the example QE file I get from CRYSPY for a RS. 

`
    &control
    title = 'Si8'
    calculation = 'relax'
    nstep = 100
    restart_mode = 'from_scratch',
    pseudo_dir = '~/calculations/subbig/pseudo'
    outdir='./out.d/'
 /

 &system
    ibrav = 0
    nat = 8
    ntyp = 1
    ecutwfc = 44.0
    occupations = 'smearing'
    degauss = 0.01
 /

 &electrons
 /

 &ions
 /

 &cell
 /

ATOMIC_SPECIES
 C 6 C.pbesol-n-kjpaw_psl.1.0.0.UPF
 N 7 N.pbesol-theos.UPF
 O 8 O.pbesol-n-kjpaw_psl.0.1.UPF
 H 1 H.pbesol-rrkjus_psl.1.0.0.UPF
CELL_PARAMETERS angstrom
   8.1848068865698647    0.7595598784348114   -3.3614435519497508
   0.0000000000000000    4.4085364017832651    1.5179270290575053
   0.0000000000000000    0.0000000000000000    8.4052731466826653
ATOMIC_POSITIONS crystal
H  1.0272744478181299 0.2627384881289004 0.0937040858057427
H  0.7599491902187562 0.4420509409689334 -0.0379224401397704
H  1.3007095992936761 -0.1762893569218246 0.1301253103079126
H  1.3893435394195548 -0.0918628105280647 0.3098480415925064
H  0.4922202182767800 0.4226243674907904 -0.0430278705054866
H  1.2803379384555376 0.1694080055216949 0.1230441804720760
H  0.4340795085209237 0.0087842692283943 0.1757403461623094
H  0.6500865178911813 -0.3590159214232218 0.4058724455370528
H  0.9157461409670384 -0.3277890657827509 0.4067927517420840
C  0.6714343797682183 -0.1906154698147080 0.3120322805532349
C  0.8609280385192991 0.0556383934057273 0.1807914373508377
C  1.1426173714168577 -0.1350332890639422 0.2454986051209205
C  0.7357180528581425 0.2795152402424241 0.0506878208188995
C  0.5793394500253902 0.2630572865696528 0.0503723761544435
C  1.2879407348735656 -0.0447281851573187 0.1963193557811781
C  0.5462998709944149 0.0248704954110217 0.1798608171398284
C  0.8290013795207284 -0.1775005144063645 0.3144883205869253
N  1.0157177154294088 0.0828068224690623 0.1677794035480051
O  1.1406391373372478 -0.3925329060627208 0.3486125988670675
K_POINTS automatic
2 4 2  0 0 0
`
1. After each section there shouldn't be a line break , it should end with forward slash only. 
2.  The order for the input is Atomic species, ATOMIC_positions angstrom, K_points automatic, and in the end cell_parameters. 

With the input file provided from the code  I get the following error: 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine read_cards (1):
     species H in ATOMIC_POSITIONS is nonexistent
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Most likely due to the wrong order of the elements in the code. 

Thank you so much for anything, any way I can help please reach out to me.

**Comment by Tomoki-YAMASHITA** [comment]
Could you give us your cryspy.in?

**Comment by yw-fang** [comment]
I think you have to make yourself exposed to several examples of quantum espresso first. Please refer to the input parameters for pw.x https://www.quantum-espresso.org/Doc/INPUT_PW.html Then you will realize that many errors in this input file for quantum espresso calculations.

To me, I think it's more likely because you are new to quantum espresso, which leads yourself set the parameters wrongly with CrySPY. For example, nat = 8 means you should have 8 atoms in the compound, however, the number of atoms in your input file obviously exceeds 8. There are many other errors. I highly recommend making the test calculations with the official examples of Quantum ESPRESSO before using CrySPY code.

**Comment by yw-fang** [comment]
By the way, the empty lines after /, and the order of the different sections don't matter and will NOT affect the execution of calculations.

**Comment by Tomoki-YAMASHITA** [comment]
I see.
@ignaciomigliaro, try the following:
```
&system
ibrav = 0
nat = 19
ntyp = 3
/
```

The cutoff needs to be changed as well.

**Comment by ignaciomigliaro** [comment]
Thank you for your prompt response, I have multiple scripts running that are generating the cryspy.in from xyz data, and I forgot to change the pwscf file.  I wasn't aware that the order of the items on the QE input file could be re-arranged, because if we look the link @yw-fang has posted, it goes from atomic species > atomic positions > k-points > cell parameters.
