### ISSUE TITLE
How to calculate RMSE for a predicted a structure and a true structure?

### ISSUE THREAD

**Issue by usccolumbia** [Tomoki-YAMASHITA/CrySPY#5]
Usually, we need to do some kind of evaluation to check the performance of the CSP algorithm.
This can be done by calculating the RMSE distance between the predicted structure and the predicted structure... Does CrySPY has such a function?

**Comment by Tomoki-YAMASHITA** [comment]
No, but CrySPY will be able to output predictive values and variance in BO. I think we can also include RMSE.

**Comment by usccolumbia** [comment]
If you can add the RMSE function to it, it will be great to evalute the performance of diff algorithms...
a reference is here
https://pyxtal.readthedocs.io/en/latest/_modules/pyxtal/operations.html#distance_matrix

**Comment by Tomoki-YAMASHITA** [comment]
Even if we evaluate the structure distance between predictive and true structures (or evaluate energy difference using RMSE), we would not be able to evaluate the performance of CSP algorithms. That is only the evaluation of accuracy of the machine learning potential. CSP includes structure generation and exploration phase.

**Comment by sgbaird** [comment]
Related: https://github.com/sparks-baird/xtal2png/issues/12

See also [pymatgen's StructureMatcher](https://pymatgen.org/pymatgen.analysis.structure_matcher.html#pymatgen.analysis.structure_matcher.StructureMatcher) and [`get_rms_dist` function](https://pymatgen.org/pymatgen.analysis.structure_matcher.html#pymatgen.analysis.structure_matcher.StructureMatcher.get_rms_dist).
