### ISSUE TITLE
two-dimensional materials

### ISSUE THREAD

**Issue by ypanhtu** [Tomoki-YAMASHITA/CrySPY#68]
Dear Developers,

Is it possible for CrySPY to search the two-dimensional materials such as by LAQA methods? If so, would you like to share some examples?

Thanks so much.

Roc 

HTU

**Comment by Tomoki-YAMASHITA** [comment]
No, CrySPY does not support 2D materials such as graphene. However, I think pyxtal supports 2D materials, so it may be possible to generate the structure manually.

This is not the Issue. Please use "Discussions" next time.

**Comment by ypanhtu** [comment]
Thank you Dr. Yamashita. 
It would be nice if the CrySPY could deal with the case of two-dimensional materials in the future version.
