### ISSUE TITLE
empty POTCAR

### ISSUE THREAD

**Issue by kexul** [Tomoki-YAMASHITA/CrySPY#7]
Hi, I'm new to CSP, I installed CrySPY and try to reproduce some example. I choosed the VASP_qsub_EA_Na8Cl8 example, but I found the POTCAR in the calc_in folder is empty, when I submit an job, there is an error: 
`POSCAR found type information on POSCAR  Na Cl`
` POSCAR found :  2 types and      16 ions`
` scaLAPACK will be used`
` ERROR: number of potentials on File POTCAR incompatible with number of species`
` INCAR :           2 POTCAR:            0`
I'm using vasp5.4.4 now, I tried switch to vasp5.4.1 but the same error occured.

**Comment by mayujie-1207** [comment]
is there a result?

**Comment by kexul** [comment]
> is there a result?

Sorry, it's a long time ago, and I no longer work in this field, I have no idea what happened next.
