### ISSUE TITLE
Could CrySPY generate 2D crystals?

### ISSUE THREAD

**Issue by sakuraiiiii** [Tomoki-YAMASHITA/CrySPY#8]
Hi. Could CrySPY generate 2D crystals randomly and how?

**Comment by Tomoki-YAMASHITA** [comment]
Sorry for late reply, I realized your comment just now.
Currently CrySPY can NOT generate random 2D crystals.
But, we will employ PyXtal library for structure generation in next version (0.9.0).
The function to generate 2D crystal might be implemented in version 0.9.x.

**Comment by sakuraiiiii** [comment]
Thanks.
